programy nanitowe, port #754
aq33/NSV13 pull request #16
Opened 2024-01-14 19:05 UTC by d-sandmann

## 📝 About The Pull Request 📝

### Port pull request-a
https://github.com/aq33/tgstation/pull/754 - dodanie nowych programów nanitowych 🤖 🐝 

## 💬 Uwagi 💬 
Za pośrednictwem konsultacji ze [Zleceniodawcą](https://github.com/Joker66613), PR #[754](https://github.com/aq33/tgstation/pull/754) był zmodyfikowany. Dodatkowo te zmiany będą wymagały testowania na serwerze, by stwierdzić, że zmiany balansu są dobre czy nie.

# 🔧 Zmiany 🔨 
- Poprawiono zachowanie tworzenia obiektu by nie robił problemów z timerami
- Zredukowano czas odnowienia programów by było można się więcej nimi cieszyć
- Zwiększono czas życia nanitowych pszczół do 20 sekund z 15
- Dodano efekt dezintegracji po upływie czasu stabilności dla tworów nanitowych, iskra jest tworzona po zniszczeniu
- Zmieniono limit programów z 20 na 40 by, było można stosować nowe kombinacje, ma to na celu dostosowanie limitu do wielu nowych programów

## Changelog
:cl: 
add: Dodano nowe programy nanitowe
add: Dodano bronie nanitowe, nóż do rzucania oraz chmare nanitowych pszczół
imageadd: Dodano wygląd nanitowego noża
imageadd: Dodano wygląd nanitowej pszczoły
soundadd: Dodano dźwięk tworzenia, aktywacji oraz śmierci nanitowej pszczoły
balance: Przebalansowano czas odnowienia programów nanitowych by było można je używać częściej
balance: Przebalansowano limit programów nanitowych z 20 na 40 by było można w pełni wykorzystać nowe funkcje
/:cl:

2024-01-14 23:43 UTC, Dejaku51 requested changes
więcej mi się nie chce kopiować i wklejać słowa modularyzacja kek

2024-01-14 23:43 UTC, Dejaku51 commented on code/__DEFINES/melee.dm
> +#define MARTIALART_NANOJUTSU "nanojutsu" // AQUILA EDIT
może daj te define do aquila

2024-01-14 23:43 UTC, Dejaku51 commented on code/__DEFINES/nanites.dm
> +#define NANITE_EXCESS_VOMIT 150 //AQUILA EDIT END
tu też

2024-01-14 23:43 UTC, Dejaku51 commented on code/__DEFINES/traits.dm
> +#define TRAIT_NANORECEIVE		"nanoreceive" //AQUILA EDIT
wsm wszedzie gdzie dodajesz define to możesz je po prostu wsadzić do aquila

2024-01-14 23:43 UTC, Dejaku51 commented on code/datums/components/nanites.dm
> +//AQUILA EDIT
raz jeszcze modularyzacja

2024-01-14 23:43 UTC, Dejaku51 commented on code/datums/components/nanites.dm
>  /datum/component/nanites/proc/set_max_volume(datum/source, amount)
zamiast tego możesz dać to w folderze aquila
```suggestion
/datum/component/nanites/set_max_volume(datum/source, amount)
	SIGNAL_HANDLER
	
	max_nanites = max(1, max_nanites)
	max_nanites = max(1, amount)
	if(nanite_volume > max_nanites)
		reject_excess_nanites()
```

2024-01-14 23:43 UTC, Dejaku51 commented on code/modules/research/nanites/nanite_programs/buffing.dm
> +	trigger_cooldown = 600 //AQUILA EDIT
tu też możesz zmodularyzować (daj to do aquila)
```suggestion
/datum/nanite_program/adrenaline
	trigger_cooldown = 600
```

2024-01-14 23:43 UTC, Dejaku51 commented on code/modules/research/nanites/nanite_programs/buffing.dm
> +	use_rate = 1 //AQUILA EDIT original value was 0,5
tak samo tutaj

2024-01-14 23:43 UTC, Dejaku51 commented on code/modules/research/nanites/nanite_programs/buffing.dm
> +	use_rate = 1 //AQUILA EDIT original value was 0,50
tak samo tutaj

2024-01-14 23:43 UTC, Dejaku51 commented on code/modules/research/nanites/nanite_programs/buffing.dm
> +	trigger_cooldown = 600 //AQUILA EDIT
tak samo tutaj

2024-01-14 23:43 UTC, Dejaku51 commented on code/modules/research/nanites/nanite_programs/suppression.dm
> +	trigger_cooldown = 300 //AQUILA EDIT
tak samo tutaj

2024-01-14 23:43 UTC, Dejaku51 commented on code/modules/research/nanites/nanite_programs/utility.dm
> +	trigger_cost = 50 //AQUILA EDIT original value was 5
tak samo tutaj

2024-01-14 23:43 UTC, Dejaku51 commented on code/modules/research/nanites/nanite_programs/utility.dm
> +//AQUILA EDIT
i tu też możesz

2024-01-14 23:43 UTC, Dejaku51 commented on code/modules/research/nanites/nanite_programs/utility.dm
> +	var/datum/nanite_extra_setting/cloud = extra_settings[NES_CLOUD_OVERWRITE] //AQUILA EDIT
tutaj też

2024-01-14 23:43 UTC, Dejaku51 commented on code/modules/research/nanites/nanite_programs/weapon.dm
> +	trigger_cooldown = 300 //AQUILA EDIT
modularyzacja

2024-01-14 23:49 UTC, d-sandmann commented
Nie wiem, to mi się wydaje na głupie, by wszystko walnąć do aquila.dm, z czasem i ilością zmian ten plik będzie komicznie duży i rakotwórczy do nawigacji.

2024-01-14 23:50 UTC, d-sandmann commented on code/modules/research/nanites/nanite_programs/weapon.dm
> +	trigger_cooldown = 300 //AQUILA EDIT
Bracie w chrystusie to jedna linijka

2024-01-15 14:36 UTC, d-sandmann commented
Zmiany się nie podobają, to zamykam. Później to dostosuje.

2024-01-15 14:36 UTC, closed without merging