fullscreen
aq33/NSV13 pull request #57
Opened 2024-01-27 10:44 UTC by d-sandmann

## About The Pull Request
Dodaje do OOC verb na pełny ekran

## Why It's Good For The Game
Pełny ekran dla wybrednych.
Modularyzacja nie jest wymagana, szansa że te pliki będą zmieniane jest komicznie niska.

## Testing Photographs and Procedure

<details>
<summary>Screenshots&Videos</summary>

Put screenshots and videos here with an empty line between the screenshots and the `<details>` tags.

![Screenshot_1](https://github.com/aq33/NSV13/assets/109915939/581a28c2-3a39-4675-901b-69779cad58fe)

![Screenshot_2](https://github.com/aq33/NSV13/assets/109915939/45df2b1a-f87a-449b-a6e4-6f15b22acaac)

![Screenshot_3](https://github.com/aq33/NSV13/assets/109915939/220dcb9b-141b-410c-8029-c4936f552ee8)
</details>

kompiluje się, brak błędów, działa jak na etykiecie, nie mam OBSa i nie umiem nagrywać ekranu to nie zrobiłem wideo demonstracji, SS chyba starczą

## Changelog
:cl:
add: Dodaje opcje na fullscreen
/:cl:

2024-01-27 10:50 UTC, d-sandmann commented
ten biały pasek na dole zawsze zostaje, bo tak pierwotnie był zrobiony klient od strony tg i tam są nazwy/opisy jak myszką najedziesz na coś

2024-01-27 11:29 UTC, MACIEKBAKI requested changes

2024-01-27 11:29 UTC, MACIEKBAKI commented on code/modules/client/verbs/ooc.dm
> +	set name = "WŁ/WYŁ Pełnyekran"
```suggestion
	set name = "Wł/Wył Pełny ekran"
```

2024-01-27 14:44 UTC, Joker66613 approved these changes

2024-01-27 15:07 UTC, d-sandmann commented
nie wiem, czy conflict resolve dobrze poszedł, bo coś mi się lokalnie zbuggowało

2024-01-27 15:14 UTC, d-sandmann commented
jest zielone więc się nic nie zepsuło po drodze

2024-01-27 17:31 UTC, srawek approved these changes

2024-01-29 22:57 UTC, d-sandmann commented
🤨

2024-01-29 22:57 UTC, closed without merging