Pakiet tłumaczeń
aq33/NSV13 pull request #73
Opened 2024-01-30 13:15 UTC by Joker66613

Pakiet tłumaczeń zebranych z przypinek na discordzie i własnych obserwacji.

2024-01-30 13:15 UTC, Joker66613 commented
To jeszcze nie koniec, ale wrzucam już teraz, żeby sobie wisiało

2024-01-31 09:24 UTC, smorgli commented on code/modules/cargo/orderconsole.dm
> +		say("Zamówienie przyjęte. PRzy dostawie kosztami zostanie obciążone konto [account.account_holder].")
PRzy

2024-01-31 09:26 UTC, smorgli commented on code/modules/clothing/masks/hailer.dm
> +					phrase_text = "Bóg dał stworzył dzisiejszy dzień byśmy połapać kryminalistów z wczoraj."
dał stworzył?

2024-01-31 09:28 UTC, smorgli commented on code/modules/clothing/masks/hailer.dm
>  					phrase_text = "Go ahead, make my day."
'No dawaj, popraw mi humor.' ?

2024-01-31 09:32 UTC, smorgli commented on code/modules/research/machinery/_production.dm
> +		say("Synchronizacja badań z bazą danych hosta.")
Baza danych programu naukowego zostala zaktualizowana

2024-01-31 09:34 UTC, smorgli commented on nsv13/code/controllers/subsystem/ranks.dm
> +		return "<span class='boldnotice'>Przwyższasz jego rangę [theirRank].</span>"
Przwyższasz

2024-01-31 09:34 UTC, smorgli commented on nsv13/code/controllers/subsystem/ranks.dm
> +		return "<span class='boldwarning'>Przewyższa cie rangą jako [myRank].</span>"
cie

2024-01-31 09:37 UTC, smorgli commented on nsv13/code/modules/mob/living/carbon/human/species_types/syndicate_knpc.dm
> +		"Podchodzę przeciwnika!"
to już atakuje by bylo lepsze niż podchodzę przeciwnika

2024-01-31 09:38 UTC, smorgli commented on nsv13/code/modules/mob/living/carbon/human/species_types/syndicate_knpc.dm
> +		"Przeciwnik dostrzeżony! Potrzebne wsparcie",
Potrzebne wsparcie w

2024-01-31 09:38 UTC, smorgli commented on nsv13/code/modules/overmap/ai-skynet.dm
> +			mini_announce("Sygnatury typu Typhonn wyktyte w [current_system]", "White Rapids EAS")
Typhonn

2024-01-31 09:42 UTC, smorgli commented on nsv13/code/modules/overmap/FTL/ftl_jump.dm
> +	relay(ftl_drive.ftl_loop, "<span class='warning'>Czujesz, że statek się nagle pochyla</span>", loop=TRUE, channel = CHANNEL_SHIP_ALERT)
Czujesz nagłe szarpnięcie statku do przodu?

2024-01-31 09:43 UTC, smorgli commented on nsv13/code/modules/overmap/factions.dm
> +			mini_announce("Sygnatury typu Typhonn wyktyte w [starsys]", "White Rapids EAS")
Typhonn

2024-01-31 09:43 UTC, smorgli commented on nsv13/code/modules/overmap/fleet_combat/combat_handling.dm
> +					minor_announce("Raporty wskazują na to, żę \a [F] podjęła walkę z  \a [EF] w [src].", "Whiterapids EAS")
żę

2024-01-31 09:44 UTC, smorgli commented on nsv13/code/modules/overmap/weapons/damage.dm
> +				priority_announce("ZAGROŻENIE. Możliwość naprawy superstruktury statku wygasła. Statek eksploduje za 5 minut.","Automated announcement ([src])","null")
przepadła?

2024-01-31 09:45 UTC, smorgli commented on strings/ion_laws.json
> +		"NIEROBOTYCZNE FORMY ŻYCIA ",
powinno być nieorganiczne czyli robotyczne, nierobotyczne to by byly organiczne

2024-02-01 15:29 UTC, MACIEKBAKI requested changes

2024-02-01 15:29 UTC, MACIEKBAKI commented on code/modules/cargo/orderconsole.dm
> +		say("Zamówienie przyjęte. PRzy dostawie kosztami zostanie obciążone konto [account.account_holder].")
```suggestion
		say("Zamówienie przyjęte. Przy dostawie kosztami zostanie obciążone konto [account.account_holder].")
```

2024-02-01 15:29 UTC, MACIEKBAKI commented on code/modules/clothing/masks/hailer.dm
> +			phrase_text = "Ty no nie wiemjak tam twoja szmaciura jebana zrogowaciała niedźwiedzica co się kurwi pod mostem za wojaka i siada kurwa na butle od vanishai kurwę w taczce pijana wozili po osiedlu
nieźle się bawiłeś przy tłumaczeniach joker, +1

2024-02-01 15:29 UTC, MACIEKBAKI commented on code/modules/clothing/masks/hailer.dm
> +					phrase_text = "Bóg dał stworzył dzisiejszy dzień byśmy połapać kryminalistów z wczoraj."
```suggestion
					phrase_text = "Bóg stworzył dzisiejszy dzień byśmy połapać kryminalistów z wczoraj."
```

2024-02-01 15:29 UTC, MACIEKBAKI commented on code/modules/clothing/masks/hailer.dm
> +					phrase_text = "Ani drgnij, szumowino!"
nie jest to poważna sugestia, ale
```suggestion
					phrase_text = "Ani drgnij, borowiku!"
```

2024-02-01 15:29 UTC, MACIEKBAKI commented on code/modules/clothing/masks/hailer.dm
>  					phrase_text = "Go ahead, make my day."
```suggestion
					phrase_text = "No dawaj, popraw mi humor."
```

2024-02-01 15:29 UTC, MACIEKBAKI commented on code/modules/events/ion_storm.dm
> +					message = "WSZYSCY LUDZIE BEZ STLOWEJ [ionhaircut] MAJĄ BYĆ ZMUSZENI DO ZMIANY FRYZURY"
```suggestion
					message = "WSZYSCY LUDZIE BEZ STYLOWEJ [ionhaircut] MAJĄ BYĆ ZMUSZENI DO ZMIANY FRYZURY"
```

2024-02-01 15:29 UTC, MACIEKBAKI commented on code/modules/events/ion_storm.dm
> +					message = "[ionobjects] SĄ SZKODLIWE I MUSZĄ ZOSTAĆ WZNISZCZONE BEZ DOPROWADZENIA DO ŚMIERCI OSÓB POSTRONNYCH"
```suggestion
					message = "[ionobjects] SĄ SZKODLIWE I MUSZĄ ZOSTAĆ ZNISZCZONE BEZ DOPROWADZENIA DO ŚMIERCI OSÓB POSTRONNYCH"
```

2024-02-01 15:29 UTC, MACIEKBAKI commented on code/modules/research/machinery/_production.dm
> +		say("Synchronizacja badań z bazą danych hosta.")
sugestia smorgli łatwa do aplikowania
```suggestion
		say("Baza danych programu naukowego została zaktualizowana.")
```

2024-02-01 15:29 UTC, MACIEKBAKI commented on nsv13/code/controllers/subsystem/overmap_mode.dm
> +							priority_announce("Automatyczny powrót do [S.name] nastąpi kiiedy zakończycie walkę.", "[mode.reminder_origin]")
```suggestion
							priority_announce("Automatyczny powrót do [S.name] nastąpi kiedy zakończycie walkę.", "[mode.reminder_origin]")
```

2024-02-01 15:29 UTC, MACIEKBAKI commented on nsv13/code/controllers/subsystem/ranks.dm
> +		return "<span class='boldnotice'>Przwyższasz jego rangę [theirRank].</span>"
```suggestion
		return "<span class='boldnotice'>Przewyższasz jego rangę jako [theirRank].</span>"
```
bez jako, jak wolisz:
```suggestion
		return "<span class='boldnotice'>Przewyższasz jego rangę [theirRank].</span>"
```

2024-02-01 15:29 UTC, MACIEKBAKI commented on nsv13/code/modules/mob/living/carbon/human/species_types/catgirl.dm
>  	)
zbrodnia wojenna

2024-02-01 15:29 UTC, MACIEKBAKI commented on nsv13/code/modules/mob/living/carbon/human/species_types/syndicate_knpc.dm
> +		"Podchodzę przeciwnika!"
```suggestion
		"Walczę z wrogiem!"
```
albo
```suggestion
		"Walczę z przeciwnikiem!"
```

2024-02-01 15:29 UTC, MACIEKBAKI commented on nsv13/code/modules/mob/living/carbon/human/species_types/syndicate_knpc.dm
> +		"Słabeusze!",
```suggestion
		"Słabeusze!",
		"Borowiki!",
```

2024-02-01 15:29 UTC, MACIEKBAKI commented on nsv13/code/modules/mob/living/carbon/human/species_types/syndicate_knpc.dm
> +		"Przeciwnik dostrzeżony! Potrzebne wsparcie",
```suggestion
		"Przeciwnik dostrzeżony! Potrzebne wsparcie w",
```

2024-02-01 15:29 UTC, MACIEKBAKI commented on nsv13/code/modules/overmap/FTL/ftl_jump.dm
> +	relay(ftl_drive.ftl_exit, "<span class='warning'>Czujesz, że statek staje</span>", loop=FALSE, channel = CHANNEL_SHIP_ALERT)
@  senonaka
ups kogoś spingowałem

2024-02-01 15:29 UTC, MACIEKBAKI commented on nsv13/code/modules/overmap/ai-skynet.dm
> +			mini_announce("Sygnatury typu Typhonn wyktyte w [current_system]", "White Rapids EAS")
```suggestion
			mini_announce("Sygnatury silnika Typhoon wykryte w [current_system]", "White Rapids EAS")
```
albo
```suggestion
			mini_announce("Sygnatury napędu Typhoon wykryte w [current_system]", "White Rapids EAS")
```

2024-02-01 15:29 UTC, MACIEKBAKI commented on nsv13/code/modules/overmap/factions.dm
> +			mini_announce("Sygnatury typu Typhonn wyktyte w [starsys]", "White Rapids EAS")
```suggestion
			mini_announce("Sygnatury napędu Typhoon wyktyte w [starsys]", "White Rapids EAS")
```
albo
```suggestion
			mini_announce("Sygnatury silnika Typhoon wyktyte w [starsys]", "White Rapids EAS")
```

2024-02-01 15:29 UTC, MACIEKBAKI commented on nsv13/code/modules/overmap/fleet_combat/combat_handling.dm
> +					minor_announce("Raporty wskazują na to, żę \a [F] podjęła walkę z  \a [EF] w [src].", "Whiterapids EAS")
```suggestion
					minor_announce("Raporty wskazują na to, że \a [F] podjęła walkę z  \a [EF] w [src].", "Whiterapids EAS")
```

2024-02-01 15:29 UTC, MACIEKBAKI commented on nsv13/code/modules/overmap/weapons/damage.dm
> +				priority_announce("ZAGROŻENIE. Możliwość naprawy superstruktury statku wygasła. Statek eksploduje za 5 minut.","Automated announcement ([src])","null")
```suggestion
				priority_announce("ZAGROŻENIE. Możliwość naprawy superstruktury statku przepadła. Statek eksploduje za 5 minut.","Automated announcement ([src])","null")
```

2024-02-01 15:29 UTC, MACIEKBAKI commented on strings/ion_laws.json
> +		"NIEROBOTYCZNE FORMY ŻYCIA ",
```suggestion
		"NIEORGANICZNE FORMY ŻYCIA ",
```

2024-02-01 15:29 UTC, MACIEKBAKI commented on strings/ion_laws.json
> +		"FORMY ŻYCIA , KTÓRE OSTATNIO POWIEDZIAŁY NYA"
```suggestion
		"FORMY ŻYCIA, KTÓRE OSTATNIO PUŚCIŁY BĄKA",
		"FORMY ŻYCIA, KTÓRE NIE NOSZĄ TORBY",
		"FORMY ŻYCIA, KTÓRE NOSZĄ PAPIEROWĄ CZAPKĘ",
		"FORMY ŻYCIA, KTÓRE NOSZĄ PLASZCZ",
		"FORMY ŻYCIA, KTÓRE NIE NOSZĄ BUTÓW",
		"FORMY ŻYCIA, KTÓRE OSTATNIO POWIEDZIAŁY NYA"
```

2024-02-01 15:29 UTC, MACIEKBAKI commented on strings/ion_laws.json
> +		"GENERATORY GRAWTIACJI",
```suggestion
		"GENERATORY GRAWITACJI",
```

2024-02-01 18:11 UTC, Joker66613 commented on code/datums/weather/weather_types/radiation_storm.dm
> +	weather_message = "<span class='userdanger'><i>Czujesz fale gorąca spływające po tobie! Znajdź schronienie!</i></span>"
no nie. fale (kogo, czego) gorąca

2024-02-01 18:26 UTC, Joker66613 commented
Dzięki za sugestie i poprawki. Większość wprowadziłem. Nie wiem jeszcze jak to "Walczę z wrogiem". Ogólnie jeszcze dodam kilka tłumaczeń, które były przypięte i wtedy będzie gotowe

2024-02-02 18:20 UTC, MACIEKBAKI commented on code/game/machinery/doppler_array.dm
>  	if(devastation_range < orig_dev_range || heavy_impact_range < orig_heavy_range || light_impact_range < orig_light_range)
dosłownie pod tym jest jeszcze nieprzetłumaczona kwestia teoretycznych wartości ttv, git nie daje mi komentować ale no

2024-02-02 18:20 UTC, MACIEKBAKI commented on code/modules/clothing/masks/hailer.dm
> +					phrase_text = "Ani drgnij, borowiku!"
kekw

2024-02-02 18:20 UTC, MACIEKBAKI commented on code/modules/events/shuttle_loan.dm
> +			priority_announce("Zaopatrzenie: Syndykat próbuje zinflitrować wasz statek. Jeśli pozwolicie im porwać prom, zaoszczędzicie nam sporo problemu.", "Kontrwywiad Centrali", SSstation.announcer.get_ra
prom sam w sobie jest troche takie ogólne, lepiej byłoby wyszczególnić np
```suggestion
			priority_announce("Zaopatrzenie: Syndykat próbuje zinflitrować wasz statek. Jeśli pozwolicie im porwać prom towarowy, zaoszczędzicie nam sporo problemu.", "Kontrwywiad Centrali", SSstation.announcer.get_rand_alert_sound())
```

2024-02-02 18:20 UTC, MACIEKBAKI commented on code/modules/events/shuttle_loan.dm
> +			priority_announce("Zaopatrzenie: Wasz statek został wybrany do epidemiologicznego programu badawczego. Wyślijce nam swój prom, a prześlemy wam próbki.", "Inicjatywa Badawcza Centrali", SSstation.a
analogicznie

2024-02-02 18:20 UTC, MACIEKBAKI commented on code/modules/events/shuttle_loan.dm
> +			SSshuttle.centcom_message += "Depeartamentowe uzupełnienie nadlatują."
```suggestion
			SSshuttle.centcom_message += "Departamentowe uzupełnienie nadlatuje."
```
albo
```suggestion
			SSshuttle.centcom_message += "Departamentowe uzupełnienia nadlatują."
```
ale uzupełnienia to dziwne tłumaczenie, czemu nie np
```suggestion
			SSshuttle.centcom_message += "Departamentowe zaopatrzenie nadlatuje."
```

2024-02-02 18:20 UTC, MACIEKBAKI commented on code/modules/events/shuttle_loan.dm
> +			SSshuttle.centcom_message += "Sprzątanie zagrożen bilogicznych nadlatuje."
```suggestion
			SSshuttle.centcom_message += "Sprzątanie zagrożeń biologicznych nadlatuje."
```

2024-02-02 18:20 UTC, MACIEKBAKI commented on nsv13/code/modules/mob/living/carbon/human/species_types/syndicate_knpc.dm
> +		"Słabeusze!",
ogólnie to syndykat to słabe borowiki

2024-02-02 18:20 UTC, MACIEKBAKI commented on nsv13/code/modules/mob/living/carbon/human/species_types/syndicate_knpc.dm
> +		"OPFOR spostrzeżony",
```suggestion
		"OPFOR spostrzeżony w",
```

2024-02-02 18:20 UTC, MACIEKBAKI commented on nsv13/code/modules/overmap/factions.dm
> +			mini_announce("Sygnatury napędu Typhoon wyktyte w [starsys]", "White Rapids EAS")
```suggestion
			mini_announce("Sygnatury napędu Typhoon wykryte w [starsys]", "White Rapids EAS")
```

2024-02-02 18:20 UTC, MACIEKBAKI commented on strings/ion_laws.json
> +		"FORMY ŻYCIA  Z UKRYTĄ TOŻSAMOŚCIĄ",
```suggestion
		"FORMY ŻYCIA BEZ OGONÓW",
		"FORMY ŻYCIA BEZ SKRZYDEŁ",
		"NIEORGANICZNE FORMY ŻYCIA ",
		"FORMY ŻYCIA Z OGONAMI",
		"FORMY ŻYCIA Z SKRZYDŁAMI",
		"FORMY ŻYCIA TRZYMAJĄCE ŹRÓDŁO ŚWIATŁA",
		"FORMY ŻYCIA TRZYMAJĄCE SKRZYNKĘ Z NARZĘDZIAMI",
		"FORMY ŻYCIA TRZYMAJĄCE GAŚNICĘ",
		"FORMY ŻYCIA Z UKRYTĄ TOŻSAMOŚCIĄ",
```
znaki białe

2024-02-02 18:20 UTC, MACIEKBAKI commented on strings/ion_laws.json
> +		"MA KREW NA SWOIM UBRAINIU",
```suggestion
		"MA KREW NA SWOIM UBRANIU",
```

2024-02-03 12:44 UTC, MACIEKBAKI approved these changes

2024-02-03 12:44 UTC, merged